In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data/revenue-data.csv')

In [3]:
data.head()

Age  SiteSpending  SiteTime  RecommendImpression Education        WorkType  \
0   32        314.06     30.14                    0    Degree  Private sector   
1   20       3758.36    149.36                    4      GCSE  Private sector   
2   36        601.72     21.87                    0   Masters  Private sector   
3   21         44.89    182.80                    9   Masters  Private sector   
4   24        614.80    194.34                    0      GCSE  Private sector   

      Sex            Region    Salary  
0    Male            London  60173.49  
1  Female        South East  42965.45  
2    Male   East of England  54924.41  
3  Female  Northern Ireland  26734.99  
4    Male          Scotland  15325.23

In [4]:
import numpy as np

In [5]:
data['£35K+ Salary'] = np.where(data['Salary'] > 35000, True, False )

In [6]:
data.tail()

Age  SiteSpending  SiteTime  RecommendImpression Education  \
995   56        177.67    272.87                    5      GCSE   
996   54        155.42    231.17                    5     Other   
997   22       2376.10    287.15                   11     Other   
998   49       4355.04     27.78                    0    Degree   
999   51         40.43    188.38                    9       PhD   

           WorkType     Sex            Region    Salary  £35K+ Salary  
995   Public Sector  Female        North West  22306.84         False  
996  Private sector    Male             Wales  27704.97         False  
997  Private sector    Male        South East  62542.89          True  
998  Private sector    Male  Northern Ireland  96745.84          True  
999  Private sector    Male        North West  48651.47          True

In [7]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

data["Education"] = le.fit_transform(data['Education'])
data["WorkType"] = le.fit_transform(data["WorkType"])
data['Sex'] = le.fit_transform(data['Sex'])
data['Region'] =  le.fit_transform(data['Region'])

In [10]:
data

Age  SiteSpending  SiteTime  RecommendImpression  Education  WorkType  \
0     32        314.06     30.14                    0          1         0   
1     20       3758.36    149.36                    4          2         0   
2     36        601.72     21.87                    0          3         0   
3     21         44.89    182.80                    9          3         0   
4     24        614.80    194.34                    0          2         0   
..   ...           ...       ...                  ...        ...       ...   
995   56        177.67    272.87                    5          2         1   
996   54        155.42    231.17                    5          5         0   
997   22       2376.10    287.15                   11          5         0   
998   49       4355.04     27.78                    0          1         0   
999   51         40.43    188.38                    9          6         0   

     Sex  Region    Salary  £35K+ Salary  
0      1       2  60173.49          True  
1      0       7  42965.45          True  
2      1       1  54924.41          True  
3      0       5  26734.99         False  
4      1       6  15325.23         False  
..   ...     ...       ...           ...  
995    0       4  22306.84         False  
996    1       9  27704.97         False  
997    1       7  62542.89          True  
998    1       5  96745.84          True  
999    1       4  48651.47          True  

[1000 rows x 10 columns]

In [19]:
#feature variables
x = data.drop(['£35K+ Salary'], axis=1)
x = x.drop(['Salary'], axis=1)
x

Age  SiteSpending  SiteTime  RecommendImpression  Education  WorkType  \
0     32        314.06     30.14                    0          1         0   
1     20       3758.36    149.36                    4          2         0   
2     36        601.72     21.87                    0          3         0   
3     21         44.89    182.80                    9          3         0   
4     24        614.80    194.34                    0          2         0   
..   ...           ...       ...                  ...        ...       ...   
995   56        177.67    272.87                    5          2         1   
996   54        155.42    231.17                    5          5         0   
997   22       2376.10    287.15                   11          5         0   
998   49       4355.04     27.78                    0          1         0   
999   51         40.43    188.38                    9          6         0   

     Sex  Region  
0      1       2  
1      0       7  
2      1       1  
3      0       5  
4      1       6  
..   ...     ...  
995    0       4  
996    1       9  
997    1       7  
998    1       5  
999    1       4  

[1000 rows x 8 columns]

In [20]:
#target variable
y = data['£35K+ Salary']
y

0       True
1       True
2       True
3      False
4      False
       ...  
995    False
996    False
997     True
998     True
999     True
Name: £35K+ Salary, Length: 1000, dtype: bool

In [21]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

## Decision Tree Classifier

In [22]:
# Create Decision Tree classifer object
model = DecisionTreeClassifier()

# Train Decision Tree Classifer
model = model.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = model.predict(x_test)

In [23]:
#Evaluation using Accuracy score
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 90.5


In [24]:
#Evaluation using Confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 56,   8],
       [ 11, 125]], dtype=int64)

In [25]:
#Evaluation using Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.84      0.88      0.85        64
        True       0.94      0.92      0.93       136

    accuracy                           0.91       200
   macro avg       0.89      0.90      0.89       200
weighted avg       0.91      0.91      0.91       200



In [26]:
#checking prediction value
model.predict([[50,40,190,9,6,1,2,4]])

C:\Users\syedi\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([ True])

In [27]:
#checking prediction value
model.predict([[20,630,174.34,0,2,0,1,5]])

C:\Users\syedi\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([False])