In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('data/revenue-data.csv')

In [5]:
data.head()

Age  SiteSpending  SiteTime  RecommendImpression Education        WorkType  \
0   32        314.06     30.14                    0    Degree  Private sector   
1   20       3758.36    149.36                    4      GCSE  Private sector   
2   36        601.72     21.87                    0   Masters  Private sector   
3   21         44.89    182.80                    9   Masters  Private sector   
4   24        614.80    194.34                    0      GCSE  Private sector   

      Sex            Region    Salary  
0    Male            London  60173.49  
1  Female        South East  42965.45  
2    Male   East of England  54924.41  
3  Female  Northern Ireland  26734.99  
4    Male          Scotland  15325.23

In [6]:
import numpy as np

In [7]:
data['£35K+ Salary'] = np.where(data['Salary'] > 35000, True, False )

In [29]:
data.tail()

Age  SiteSpending  SiteTime  RecommendImpression Education  \
995   56        177.67    272.87                    5      GCSE   
996   54        155.42    231.17                    5     Other   
997   22       2376.10    287.15                   11     Other   
998   49       4355.04     27.78                    0    Degree   
999   51         40.43    188.38                    9       PhD   

           WorkType     Sex            Region    Salary  £35K+ Salary  
995   Public Sector  Female        North West  22306.84         False  
996  Private sector    Male             Wales  27704.97         False  
997  Private sector    Male        South East  62542.89          True  
998  Private sector    Male  Northern Ireland  96745.84          True  
999  Private sector    Male        North West  48651.47          True

In [25]:
data.pivot_table(columns=['Education'], aggfunc='size')

Education
A Level    136
Degree     282
GCSE       103
Masters    119
None        61
Other      141
PhD        158
dtype: int64

In [26]:
data.pivot_table(columns=['WorkType'], aggfunc='size')

WorkType
Private sector    612
Public Sector     124
Self Employed      15
Unemployed        249
dtype: int64

In [27]:
data.pivot_table(columns=['Region'], aggfunc='size')

Region
East Midlands                59
East of England              79
London                      110
North East                   26
North West                   91
Northern Ireland             62
Scotland                    158
South East                  138
South West                   71
Wales                        47
West Midlands                78
Yorkshire and The Humber     81
dtype: int64

In [28]:
data.pivot_table(columns=['Sex'], aggfunc='size')

Sex
Female    544
Male      456
dtype: int64

In [15]:
#feature variables
x = data.drop(['£35K+ Salary'], axis=1)
x = x.drop(['Salary'], axis=1)
x = x.drop(['Education'], axis=1)
x = x.drop(['WorkType'], axis=1)
x = x.drop(['Sex'], axis=1)
x = x.drop(['Region'], axis=1)
x

Age  SiteSpending  SiteTime  RecommendImpression
0     32        314.06     30.14                    0
1     20       3758.36    149.36                    4
2     36        601.72     21.87                    0
3     21         44.89    182.80                    9
4     24        614.80    194.34                    0
..   ...           ...       ...                  ...
995   56        177.67    272.87                    5
996   54        155.42    231.17                    5
997   22       2376.10    287.15                   11
998   49       4355.04     27.78                    0
999   51         40.43    188.38                    9

[1000 rows x 4 columns]

In [11]:
#target variable
y = data['£35K+ Salary']
y

0       True
1       True
2       True
3      False
4      False
       ...  
995    False
996    False
997     True
998     True
999     True
Name: £35K+ Salary, Length: 1000, dtype: bool

In [17]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [18]:
# Create Decision Tree classifer object
model = DecisionTreeClassifier()

# Train Decision Tree Classifer
model = model.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = model.predict(x_test)

In [19]:
#Evaluation using Accuracy score
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 93.0


In [20]:
#Evaluation using Confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 58,   6],
       [  8, 128]], dtype=int64)

In [21]:
#Evaluation using Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.88      0.91      0.89        64
        True       0.96      0.94      0.95       136

    accuracy                           0.93       200
   macro avg       0.92      0.92      0.92       200
weighted avg       0.93      0.93      0.93       200



In [24]:
#checking prediction value
model.predict([[22,50,170,6]])

C:\Users\syedi\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([False])

In [30]:
#checking prediction value
model.predict([[50,50,180,7]])

C:\Users\syedi\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([ True])